// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// maxexceptfor
NumericVector maxexceptfor(NumericVector vec, int ele);
RcppExport SEXP _ODENEM_maxexceptfor(SEXP vecSEXP, SEXP eleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type ele(eleSEXP);
    rcpp_result_gen = Rcpp::wrap(maxexceptfor(vec, ele));
    return rcpp_result_gen;
END_RCPP
}
// rcppLikelihood
double rcppLikelihood(List model, Function compute_states, Function gammas, Function ddens1, Function ddens0, Function WT_R, Function input, String method, double ts);
RcppExport SEXP _ODENEM_rcppLikelihood(SEXP modelSEXP, SEXP compute_statesSEXP, SEXP gammasSEXP, SEXP ddens1SEXP, SEXP ddens0SEXP, SEXP WT_RSEXP, SEXP inputSEXP, SEXP methodSEXP, SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Function >::type compute_states(compute_statesSEXP);
    Rcpp::traits::input_parameter< Function >::type gammas(gammasSEXP);
    Rcpp::traits::input_parameter< Function >::type ddens1(ddens1SEXP);
    Rcpp::traits::input_parameter< Function >::type ddens0(ddens0SEXP);
    Rcpp::traits::input_parameter< Function >::type WT_R(WT_RSEXP);
    Rcpp::traits::input_parameter< Function >::type input(inputSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppLikelihood(model, compute_states, gammas, ddens1, ddens0, WT_R, input, method, ts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ODENEM_maxexceptfor", (DL_FUNC) &_ODENEM_maxexceptfor, 2},
    {"_ODENEM_rcppLikelihood", (DL_FUNC) &_ODENEM_rcppLikelihood, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_ODENEM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
