# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

maxexceptfor <- function(vec, ele) {
    .Call(`_ODENEM_maxexceptfor`, vec, ele)
}

rcppLikelihood <- function(model, compute_states, gammas, ddens1, ddens0, WT_R, input, method, ts) {
    .Call(`_ODENEM_rcppLikelihood`, model, compute_states, gammas, ddens1, ddens0, WT_R, input, method, ts)
}

